import { Asset } from './types';

export const INITIAL_ASSETS: Asset[] = [
  {
    symbol: "XAU/USD",
    name: "Emas Spot / US Dollar",
    category: "FOREX",
    price: 2314.50,
    prevPrice: 2309.20,
    change24h: 0.23,
    high24h: 2325.80,
    low24h: 2302.10,
    tradingViewSymbol: "OANDA:XAUUSD",
    rating: "★★★★★ (4.9)",
    creator: "MARKET: FX",
    volume: "1,424K",
    theme: "yellow",
    tags: ["hot", "trending", "safe-haven"],
    description: "Emas spot terhadap Dolar AS. Komoditas pelindung nilai (safe haven) utama dunia dengan volatilitas tinggi."
  },
  {
    symbol: "BTC/USD",
    name: "Bitcoin / US Dollar",
    category: "CRYPTO",
    price: 67120.00,
    prevPrice: 65450.00,
    change24h: 2.55,
    high24h: 67800.00,
    low24h: 65110.00,
    coinGeckoId: "bitcoin",
    tradingViewSymbol: "BINANCE:BTCUSDT",
    rating: "★★★★★ (4.8)",
    creator: "COINGECKO",
    volume: "9,890K",
    theme: "purple",
    tags: ["hot", "trending", "crypto"],
    description: "Bitcoin spot terhadap USD. Raja Cryptocurrency global dengan likuiditas raksasa dan kapitalisasi pasar terbesar."
  },
  {
    symbol: "ETH/USD",
    name: "Ethereum / US Dollar",
    category: "CRYPTO",
    price: 3485.20,
    prevPrice: 3515.50,
    change24h: -0.86,
    high24h: 3540.00,
    low24h: 3450.10,
    coinGeckoId: "ethereum",
    tradingViewSymbol: "BINANCE:ETHUSDT",
    rating: "★★★★☆ (4.5)",
    creator: "COINGECKO",
    volume: "5,110K",
    theme: "pink",
    tags: ["trending", "crypto"],
    description: "Ethereum terhadap USD. Platform smart-contract terkemuka dengan ekosistem finansial terdesentralisasi (DeFi) terbesar."
  },
  {
    symbol: "SOL/USD",
    name: "Solana / US Dollar",
    category: "CRYPTO",
    price: 145.75,
    prevPrice: 139.10,
    change24h: 4.78,
    high24h: 148.90,
    low24h: 137.20,
    coinGeckoId: "solana",
    dexScreenerId: "solana/EP2ibZ7nRLX6Du7YnS1rAZX4U7B6654eN9", // Sol pair search
    tradingViewSymbol: "BINANCE:SOLUSDT",
    rating: "★★★★★ (4.7)",
    creator: "DEXSCREENER",
    volume: "3,440K",
    theme: "blue",
    tags: ["hot", "new", "crypto"],
    description: "Token gas Solana berkecepatan ultra-tinggi. Likuiditas tinggi bersumber dari DEX & CEX terdesentralisasi global."
  },
  {
    symbol: "TSLA/USD",
    name: "Tesla, Inc. Common Stock",
    category: "STOCKS",
    price: 187.44,
    prevPrice: 184.10,
    change24h: 1.81,
    high24h: 189.20,
    low24h: 182.50,
    tradingViewSymbol: "NASDAQ:TSLA",
    rating: "★★★★☆ (4.2)",
    creator: "MARKET: US",
    volume: "890K",
    theme: "green",
    tags: ["trending", "stocks"],
    description: "Saham Tesla Motors Inc. Saham teknologi otomotif listrik global berkapitalisasi masif dengan pergerakan volatil."
  },
  {
    symbol: "NVDA/USD",
    name: "NVIDIA Corporation Stock",
    category: "STOCKS",
    price: 127.40,
    prevPrice: 120.30,
    change24h: 5.90,
    high24h: 129.50,
    low24h: 119.80,
    tradingViewSymbol: "NASDAQ:NVDA",
    rating: "★★★★★ (4.9)",
    creator: "MARKET: US",
    volume: "2,100K",
    theme: "purple",
    tags: ["hot", "new", "stocks"],
    description: "Saham Nvidia Corp. Peneraju utama revolusi sirkuit mikro kecerdasan buatan (AI) & unit pemrosesan grafis (GPU) dunia."
  },
  {
    symbol: "EUR/USD",
    name: "Euro / US Dollar Spot",
    category: "FOREX",
    price: 1.07340,
    prevPrice: 1.07450,
    change24h: -0.10,
    high24h: 1.07620,
    low24h: 1.07180,
    tradingViewSymbol: "FX:EURUSD",
    rating: "★★★☆☆ (3.9)",
    creator: "MARKET: FX",
    volume: "8,920K",
    theme: "pink",
    tags: ["stable", "forex"],
    description: "Mata uang gabungan Euro terhadap Dolar Amerika Serikat. Likuiditas terpadat di dunia dengan spread transaksi sangat tipis."
  },
  {
    symbol: "GBP/USD",
    name: "British Pound / US Dollar Exchange",
    category: "FOREX",
    price: 1.26840,
    prevPrice: 1.26510,
    change24h: 0.26,
    high24h: 1.27100,
    low24h: 1.26250,
    tradingViewSymbol: "FX:GBPUSD",
    rating: "★★★★☆ (4.1)",
    creator: "MARKET: FX",
    volume: "4,150K",
    theme: "yellow",
    tags: ["forex"],
    description: "Poundsterling Britania Raya terhadap Dolar AS. Pasangan mata uang klasik dengan volatilitas tinggi saat rilis berita ekonomi London."
  }
];

export const RETRO_COMMANDS = [
  { cmd: "help", desc: "Tampilkan menu bantuan terminal." },
  { cmd: "status", desc: "Cek kestabilan koneksi bursa dan status portfolio." },
  { cmd: "assets", desc: "Tampilkan seluruh pasangan instrumen aktif." },
  { cmd: "positions", desc: "Tampilkan seluruh posisi floating saat ini." },
  { cmd: "buy <symbol> <qty> [sl] [tp]", desc: "Buka posisi pembelian (LONG) instrumen." },
  { cmd: "sell <symbol> <qty> [sl] [tp]", desc: "Buka posisi penjualan (SHORT) instrumen." },
  { cmd: "close <id>", desc: "Tutup paksa posisi aktif berdasarkan ID." },
  { cmd: "api-status", desc: "Tampilkan status integrasi feed CoinGecko & DexScreener." },
  { cmd: "clear", desc: "Bersihkan log monitor terminal." }
];
